= Задачи

== Задание 1

Напишите функцию to_dict(lst), которая принимает аргумент в виде списка и возвращает словарь, в котором каждый элемент списка является и ключом и значением. Предполагается, что элементы списка будут соответствовать правилам задания ключей в словарях.

== Задание 2

Создайте словарь с количеством элементов не менее 5-ти. Поменяйте местами первый и последний элемент объекта. Удалите второй элемент. Добавьте в конец ключ «new_key» со значением «new_value». Выведите на печать итоговый словарь. Важно, чтобы словарь остался тем же (имел тот же адрес в памяти).

== Задание 3

Имеется ряд словарей с пересекающимися ключами (значения - положительные числа). Напишите 2 функции, которые делают с массивом словарей следующие операции.

=== Операция 1

Функция `max_dct(*dicts)` формирует новый словарь по правилу:

* Если в исходных словарях есть повторяющиеся ключи, выбираем среди их значений максимальное и присваиваем этому ключу (например, в словаре_1 есть ключ "`а`" со значением 5, и в словаре_2 есть ключ "`а`", но со значением 9. Выбираем максимальное значение, т. е. 9, и присваиваем ключу "`а`" в уже новом словаре).  
* Если ключ не повторяется, то он просто переносится со своим значением в новый словарь (например, ключ "`с`" встретился только у одного словаря, а у других его нет. Следовательно, переносим в новый словарь этот ключ вместе с его значением). Сформированный словарь возвращаем.

=== Операция 2

функция `sum_dct(*dicts)` суммирует значения повторяющихся ключей. Значения остальных ключей остаются исходными. (Проводятся операции по аналогу первой функции, но берутся не максимумы, а суммы значений одноименных ключей). Функция возвращает сформированный словарь.


---

Все задания выполнены Itachi
