= SuDoku

SuDoku (в переводе с японского означает числовое место) — это название, данное популярной концепции головоломки. Его происхождение неясно, но следует отдать должное Леонарду Эйлеру, который изобрел аналогичную, но гораздо более сложную идею головоломки под названием "`Латинские квадраты`".Однако цель головоломок SuDoku состоит в том, чтобы заменить пробелы (или нули) в сетке 9 на 9 таким образом, чтобы каждая строка, столбец и поле 3 на 3 содержали каждую из цифр от 1 до 9.

Хорошо построенная головоломка SuDoku имеет уникальное решение и может быть решена с помощью логики, хотя может потребоваться использование методов «догадки и проверки», чтобы исключить варианты (по этому поводу существует много спорных мнений). Сложность поиска определяет сложность головоломки; приведенный выше пример считается простым, потому что его можно решить с помощью прямого вывода.

Текстовый файл `sudoku`, содержит десять различных головоломок SuDoku различной сложности, но все с уникальными решениями. Решив все десять головоломок, найдите сумму трехзначных чисел, найденных в верхнем левом углу каждой сетки решения.
